install.packages("rmarkdown")
install.packages("httr")
install.packages('caTools')
install.packages('rprojroot')
install.packages('ggplot2')
if (!require(devtools)) install.packages('devtools')
devtools::install_github("giswqs/whiteboxR")
